### ISSUE TITLE
Expose type parser

### ISSUE THREAD

**Issue by pauldijou** [elm-lang/project-metadata-utils#2]
Would it be ok to expose the `tipe: Parser Type` from `Elm.Docs.Type` so that people can reuse it without having to re-implement it or fork the project? I can do a PR if that's cool with you.

(as for the use-case, we want more infos about our project at work so we are working on a parser that will returns us all we need to know)

**Comment by evancz** [comment]
It is not a general purpose parser. If you want to parse Elm, it will not help you because it does not do anything about indentation.
